### PR TITLE
update for ghc-7.6

### PR DESCRIPTION
**Pull request by JohnLato**
I've made the necessary modifications for vacuum to build with ghc-7.6.  ghc's closure types don't appear to have changed, but I made a new module (and hence the version bump) anyway.

### CODE REVIEW

**Comment by thoughtpolice** [comment]
I've been aware of this since the RC but haven't had time to give Vacuum as much love as I wanted. Thank you for doing this! I will merge and cut a release tonight.

**Comment by JohnLato** [comment]
great, thanks!

**Comment by thoughtpolice** [comment]
I merged this manually with you as the author in f3a39a5ed94d835f91fc695a2e9987ef03ae288f - I do this mostly because I use a scheme for 'signing' off patches from 3rd parties with `Acked-by` for review. It's just a convention I've adopted. Also, I bumped and tagged the version myself because I normally cryptographically sign the tags with my GPG key for all the projects I maintain/write.

For some reason GitHub didn't resolve the author information to your username. :( Sorry about that!

**Comment by JohnLato** [comment]
Thanks very much for the update and release.  No worries about the author
info.

**Pull request closed without merging**
